tuturails/config/routes.rb
Rails.application.routes.draw do
  resources :trains
  resources :railway_stations
  resources :routes

  get 'welcome/index'

  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

tuturails/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

tuturails/app/models/railway_station.rb
class RailwayStation < ApplicationRecord
  validates :title. presence: true

  has_many :trains
end

tuturails/app/models/route.rb
class Route < ApplicationRecord
  validates :title, presence: true
end

tuturails/app/models/train.rb
class Train < ApplicationRecord
  validates :number, presence: true

  belongs_to :railway_station
end

tuturails/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

tuturails/app/controllers/railway_stations_controller.rb
class RailwayStationsController < ApplicationController
  before_action :set_railway_station, only: [:show, :edit, :update, :destroy]

  # GET /railway_stations
  # GET /railway_stations.json
  def index
    @railway_stations = RailwayStation.all
  end

  # GET /railway_stations/1
  # GET /railway_stations/1.json
  def show
  end

  # GET /railway_stations/new
  def new
    @railway_station = RailwayStation.new
  end

  # GET /railway_stations/1/edit
  def edit
  end

  # POST /railway_stations
  # POST /railway_stations.json
  def create
    @railway_station = RailwayStation.new(railway_station_params)

    respond_to do |format|
      if @railway_station.save
        format.html { redirect_to @railway_station, notice: 'Railway station was successfully created.' }
        format.json { render :show, status: :created, location: @railway_station }
      else
        format.html { render :new }
        format.json { render json: @railway_station.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /railway_stations/1
  # PATCH/PUT /railway_stations/1.json
  def update
    respond_to do |format|
      if @railway_station.update(railway_station_params)
        format.html { redirect_to @railway_station, notice: 'Railway station was successfully updated.' }
        format.json { render :show, status: :ok, location: @railway_station }
      else
        format.html { render :edit }
        format.json { render json: @railway_station.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /railway_stations/1
  # DELETE /railway_stations/1.json
  def destroy
    @railway_station.destroy
    respond_to do |format|
      format.html { redirect_to railway_stations_url, notice: 'Railway station was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_railway_station
      @railway_station = RailwayStation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def railway_station_params
      params.require(:railway_station).permit(:title)
    end
end

tuturails/app/controllers/routes_controller.rb
class RoutesController < ApplicationController
  before_action :set_route, only: [:show, :edit, :update, :destroy]

  def index
    @routes = Route.all
  end

  def show
  end

  def new
    @route = Route.new
  end

  def create
    @route = Route.new(route_params)

    if @route.save
      redirect_to @route
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @route.update(route_params)
      redirect_to @route
    else
      render :new
    end
  end

  def destroy
    @route.destroy
    redirect_to routes_path
  end

  private

  def route_params
    params.require(:route).permit(:title)
  end

  def set_route
    @route = Route.find(params[:id])
  end
end

tuturails/app/controllers/trains_controller.rb
class TrainsController < ApplicationController
  before_action :set_train, only: [:show, :edit, :update, :destroy]

  # GET /trains
  # GET /trains.json
  def index
    @trains = Train.all
  end

  # GET /trains/1
  # GET /trains/1.json
  def show
  end

  # GET /trains/new
  def new
    @train = Train.new
  end

  # GET /trains/1/edit
  def edit
  end

  # POST /trains
  # POST /trains.json
  def create
    @train = Train.new(train_params)

    respond_to do |format|
      if @train.save
        format.html { redirect_to @train, notice: 'Train was successfully created.' }
        format.json { render :show, status: :created, location: @train }
      else
        format.html { render :new }
        format.json { render json: @train.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trains/1
  # PATCH/PUT /trains/1.json
  def update
    respond_to do |format|
      if @train.update(train_params)
        format.html { redirect_to @train, notice: 'Train was successfully updated.' }
        format.json { render :show, status: :ok, location: @train }
      else
        format.html { render :edit }
        format.json { render json: @train.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trains/1
  # DELETE /trains/1.json
  def destroy
    @train.destroy
    respond_to do |format|
      format.html { redirect_to trains_url, notice: 'Train was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_train
      @train = Train.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def train_params
      params.require(:train).permit(:number)
    end
end

tuturails/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

tuturails/app/helpers/application_helper.rb
module ApplicationHelper
end

tuturails/app/helpers/railway_stations_helper.rb
module RailwayStationsHelper
end

tuturails/app/helpers/trains_helper.rb
module TrainsHelper
end

tuturails/app/helpers/welcome_helper.rb
module WelcomeHelper
end

tuturails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tuturails</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

tuturails/app/views/railway_stations/_form.html.erb
<%= form_for(railway_station) do |f| %>
  <% if railway_station.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(railway_station.errors.count, "error") %> prohibited this railway_station from being saved:</h2>

      <ul>
      <% railway_station.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

tuturails/app/views/railway_stations/edit.html.erb
<h1>Editing Railway Station</h1>

<%= render 'form', railway_station: @railway_station %>

<%= link_to 'Show', @railway_station %> |
<%= link_to 'Back', railway_stations_path %>

tuturails/app/views/railway_stations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Railway Stations</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @railway_stations.each do |railway_station| %>
      <tr>
        <td><%= railway_station.title %></td>
        <td><%= link_to 'Show', railway_station %></td>
        <td><%= link_to 'Edit', edit_railway_station_path(railway_station) %></td>
        <td><%= link_to 'Destroy', railway_station, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Railway Station', new_railway_station_path %>

tuturails/app/views/railway_stations/new.html.erb
<h1>New Railway Station</h1>

<%= render 'form', railway_station: @railway_station %>

<%= link_to 'Back', railway_stations_path %>

tuturails/app/views/railway_stations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @railway_station.title %>
</p>

<%= link_to 'Edit', edit_railway_station_path(@railway_station) %> |
<%= link_to 'Back', railway_stations_path %>

tuturails/app/views/routes/edit.html.erb
<h1>Редактировать путь</h1>

<%= form_for(@route) do |f| %>
  <% if @route.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@route.errors.count, "error") %> prohibited this train from being saved:</h2>

      <ul>
      <% @route.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="actions">
    <%= f.submit 'Создать'%>
  </div>
<% end %>

<%= link_to 'Показать', @route %> |
<%= link_to 'Назад', routes_path %>

tuturails/app/views/routes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Routes</h1>

<table>
  <thead>
    <tr>
      <th>Number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @routes.each do |route| %>
      <tr>
        <td><%= route.title %></td>
        <td><%= link_to 'Показать', route %></td>
        <td><%= link_to 'Исправить', edit_route_path(route) %></td>
        <td><%= link_to 'Удалить', route, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Route', new_route_path %>

tuturails/app/views/routes/new.html.erb
<h1>Новый путь</h1>

<%= form_for(@route) do |f| %>
  <% if @route.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@route.errors.count, "error") %> prohibited this train from being saved:</h2>

      <ul>
      <% @route.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="actions">
    <%= f.submit 'Создать'%>
  </div>
<% end %>


<%= link_to 'Back', routes_path %>

tuturails/app/views/routes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Название:</strong>
  <%= @route.title %>
</p>

<%= link_to 'Исправить', edit_route_path(@route) %> |
<%= link_to 'Назад', routes_path %>

tuturails/app/views/trains/_form.html.erb
<%= form_for(train) do |f| %>
  <% if train.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(train.errors.count, "error") %> prohibited this train from being saved:</h2>

      <ul>
      <% train.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :number %>
    <%= f.number_field :number %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

tuturails/app/views/trains/edit.html.erb
<h1>Editing Train</h1>

<%= render 'form', train: @train %>

<%= link_to 'Show', @train %> |
<%= link_to 'Back', trains_path %>

tuturails/app/views/trains/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Trains</h1>

<table>
  <thead>
    <tr>
      <th>Number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @trains.each do |train| %>
      <tr>
        <td><%= train.number %></td>
        <td><%= link_to 'Show', train %></td>
        <td><%= link_to 'Edit', edit_train_path(train) %></td>
        <td><%= link_to 'Destroy', train, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Train', new_train_path %>

tuturails/app/views/trains/new.html.erb
<h1>New Train</h1>

<%= render 'form', train: @train %>

<%= link_to 'Back', trains_path %>

tuturails/app/views/trains/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Number:</strong>
  <%= @train.number %>
</p>

<%= link_to 'Edit', edit_train_path(@train) %> |
<%= link_to 'Back', trains_path %>

tuturails/app/views/welcome/index.html.erb
<h1>Привет, Rails!!!</h1>
<%= link_to 'Список станций', railway_stations_path %>
<%= link_to 'Список поездов', trains_path %>
<%= link_to 'Список путей', routes_path %>